import { College } from './types';

export const MOCK_COLLEGES: College[] = [
  {
    id: 'iit-bombay',
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    fees: { min: 200000, max: 250000 },
    rating: 4.8,
    reviewCount: 2847,
    placementPercentage: 98,
    averagePackage: 28,
    highestPackage: 3,
    description: 'IIT Bombay is one of the most prestigious engineering institutions in India. Established in 1958, it is known for its excellent academics, cutting-edge research, and outstanding placement record. The institute offers undergraduate, postgraduate, and doctoral programs in engineering, science, design, and management.',
    established: 1958,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 3,
    tags: ['IIT', 'NIRF Top 5', 'Govt. Funded', 'Premium'],
    facilities: ['Library', 'Sports Complex', 'Hostel', 'Research Labs', 'Innovation Hub', 'Medical Center', 'Swimming Pool'],
    website: 'https://www.iitb.ac.in',
    totalStudents: 10500,
    campusArea: '550 acres',
    topRecruiters: [
      { name: 'Google', package: 130 },
      { name: 'Microsoft', package: 95 },
      { name: 'Goldman Sachs', package: 85 },
      { name: 'McKinsey', package: 60 },
      { name: 'Amazon', package: 55 },
    ],
    courses: [
      { id: 'btech-cs', name: 'B.Tech Computer Science', duration: '4 Years', fees: 225000, seats: 120, eligibility: 'JEE Advanced', degree: 'B.Tech' },
      { id: 'btech-ee', name: 'B.Tech Electrical Engineering', duration: '4 Years', fees: 225000, seats: 90, eligibility: 'JEE Advanced', degree: 'B.Tech' },
      { id: 'mtech-cs', name: 'M.Tech Computer Science', duration: '2 Years', fees: 180000, seats: 60, eligibility: 'GATE', degree: 'M.Tech' },
      { id: 'mba', name: 'MBA (SJMSOM)', duration: '2 Years', fees: 750000, seats: 120, eligibility: 'CAT', degree: 'MBA' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Arjun Sharma', rating: 5, comment: 'Best college in India for engineering. World-class faculty and incredible peer learning environment. Placements are amazing!', date: '2024-03-15', helpful: 245, aspects: { academics: 5, campus: 5, placements: 5, faculty: 5 } },
      { id: 'r2', userId: 'u2', userName: 'Priya Patel', rating: 4, comment: 'Excellent research opportunities and stellar faculty. Campus life is vibrant with numerous clubs. A bit stressful with academics but totally worth it.', date: '2024-01-20', helpful: 189, aspects: { academics: 5, campus: 4, placements: 5, faculty: 4 } },
    ],
  },
  {
    id: 'iit-delhi',
    name: 'Indian Institute of Technology Delhi',
    shortName: 'IIT Delhi',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    fees: { min: 190000, max: 240000 },
    rating: 4.7,
    reviewCount: 2543,
    placementPercentage: 97,
    averagePackage: 27,
    highestPackage: 2,
    description: 'IIT Delhi, established in 1961, is one of India\'s top engineering institutes, located in the heart of New Delhi. Renowned for its engineering, technology, and research excellence, IIT Delhi consistently ranks among the best institutions globally.',
    established: 1961,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 2,
    tags: ['IIT', 'NIRF Top 5', 'Govt. Funded', 'Research'],
    facilities: ['Central Library', 'Olympic-size Pool', 'Hostel', 'Health Center', 'Innovation Center'],
    website: 'https://www.iitd.ac.in',
    totalStudents: 9800,
    campusArea: '325 acres',
    topRecruiters: [
      { name: 'Microsoft', package: 120 },
      { name: 'Apple', package: 110 },
      { name: 'Bain & Company', package: 72 },
      { name: 'JP Morgan', package: 68 },
      { name: 'Adobe', package: 52 },
    ],
    courses: [
      { id: 'btech-cs', name: 'B.Tech Computer Science', duration: '4 Years', fees: 220000, seats: 105, eligibility: 'JEE Advanced', degree: 'B.Tech' },
      { id: 'btech-mech', name: 'B.Tech Mechanical Engineering', duration: '4 Years', fees: 200000, seats: 80, eligibility: 'JEE Advanced', degree: 'B.Tech' },
      { id: 'mba', name: 'MBA (DMS)', duration: '2 Years', fees: 650000, seats: 90, eligibility: 'CAT', degree: 'MBA' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Rohit Verma', rating: 5, comment: 'IIT Delhi is in an unbeatable location in Hauz Khas. The campus vibe is electric and the alumni network is world-class.', date: '2024-02-10', helpful: 198, aspects: { academics: 5, campus: 5, placements: 5, faculty: 5 } },
    ],
  },
  {
    id: 'iim-ahmedabad',
    name: 'Indian Institute of Management Ahmedabad',
    shortName: 'IIM-A',
    location: 'Ahmedabad, Gujarat',
    city: 'Ahmedabad',
    state: 'Gujarat',
    fees: { min: 2300000, max: 2500000 },
    rating: 4.9,
    reviewCount: 1876,
    placementPercentage: 100,
    averagePackage: 35,
    highestPackage: 85,
    description: 'IIM Ahmedabad is the top-ranked business school in India and among the best in Asia. Known for its rigorous curriculum, case study pedagogy, and phenomenal placements. The stunning Louis Kahn campus is an architectural masterpiece.',
    established: 1961,
    type: 'Government',
    accreditation: 'AACSB, AMBA, EQUIS',
    nirfRank: 1,
    tags: ['IIM', 'Top MBA', 'Triple Crown', 'Leadership'],
    facilities: ['Library', 'Sports Complex', 'Hostel', 'Amphitheatre', 'Innovation Hub', 'Global Network'],
    website: 'https://www.iima.ac.in',
    totalStudents: 1800,
    campusArea: '100 acres',
    topRecruiters: [
      { name: 'BCG', package: 85 },
      { name: 'McKinsey', package: 80 },
      { name: 'Bain', package: 72 },
      { name: 'Goldman Sachs', package: 65 },
      { name: 'Amazon', package: 48 },
    ],
    courses: [
      { id: 'pgp', name: 'Post Graduate Programme (MBA)', duration: '2 Years', fees: 2400000, seats: 385, eligibility: 'CAT', degree: 'MBA' },
      { id: 'pgpx', name: 'PGP for Executives', duration: '1 Year', fees: 3200000, seats: 70, eligibility: 'CAT/GMAT', degree: 'MBA' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Kavita Nair', rating: 5, comment: 'IIMA transformed my career completely. The case study method of teaching is phenomenal. The alumni network opens doors everywhere in the world.', date: '2024-04-05', helpful: 412, aspects: { academics: 5, campus: 5, placements: 5, faculty: 5 } },
    ],
  },
  {
    id: 'bits-pilani',
    name: 'Birla Institute of Technology and Science, Pilani',
    shortName: 'BITS Pilani',
    location: 'Pilani, Rajasthan',
    city: 'Pilani',
    state: 'Rajasthan',
    fees: { min: 550000, max: 650000 },
    rating: 4.5,
    reviewCount: 3210,
    placementPercentage: 92,
    averagePackage: 18,
    highestPackage: 1,
    description: 'BITS Pilani is India\'s premier private technical university. Known for its unique dual-degree programs, practice school, and strong industry connections, BITS consistently produces top engineers and entrepreneurs.',
    established: 1964,
    type: 'Deemed',
    accreditation: 'NAAC A',
    nirfRank: 25,
    tags: ['BITS', 'Top Private', 'Practice School', 'Entrepreneurship'],
    facilities: ['Central Library', 'Sports Complex', 'Medical Center', 'Hostels', 'Startup Hub'],
    website: 'https://www.bits-pilani.ac.in',
    totalStudents: 7500,
    campusArea: '328 acres',
    topRecruiters: [
      { name: 'Google', package: 80 },
      { name: 'Uber', package: 55 },
      { name: 'Zomato', package: 45 },
      { name: 'NVIDIA', package: 70 },
      { name: 'Razorpay', package: 40 },
    ],
    courses: [
      { id: 'be-cs', name: 'B.E. Computer Science', duration: '4 Years', fees: 600000, seats: 150, eligibility: 'BITSAT', degree: 'B.E.' },
      { id: 'be-ece', name: 'B.E. Electronics & Communication', duration: '4 Years', fees: 600000, seats: 110, eligibility: 'BITSAT', degree: 'B.E.' },
      { id: 'msc-physics', name: 'M.Sc. Physics', duration: '2 Years', fees: 250000, seats: 40, eligibility: 'BITSAT', degree: 'M.Sc.' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Nikhil Mehta', rating: 5, comment: 'BITS Pilani is pure gold. The freedom you get here is unparalleled. Practice School is the best industry exposure you can get as an undergrad.', date: '2024-03-01', helpful: 321, aspects: { academics: 5, campus: 4, placements: 4, faculty: 4 } },
    ],
  },
  {
    id: 'nit-trichy',
    name: 'National Institute of Technology Tiruchirappalli',
    shortName: 'NIT Trichy',
    location: 'Tiruchirappalli, Tamil Nadu',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    fees: { min: 120000, max: 180000 },
    rating: 4.4,
    reviewCount: 1987,
    placementPercentage: 88,
    averagePackage: 13,
    highestPackage: 0,
    description: 'NIT Trichy is consistently ranked as the top NIT in India. Known for its excellent faculty, research output, and strong placement record, it offers programs in engineering, architecture, and management.',
    established: 1964,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 8,
    tags: ['NIT', 'NIRF Top 10', 'Govt. Funded', 'Architecture'],
    facilities: ['Central Library', 'Sports Ground', 'Hostel', 'Health Center', 'Research Centers'],
    website: 'https://www.nitt.edu',
    totalStudents: 8200,
    campusArea: '800 acres',
    topRecruiters: [
      { name: 'TCS', package: 7 },
      { name: 'Wipro', package: 6.5 },
      { name: 'Infosys', package: 7 },
      { name: 'Qualcomm', package: 28 },
      { name: 'Samsung', package: 22 },
    ],
    courses: [
      { id: 'btech-cse', name: 'B.Tech CSE', duration: '4 Years', fees: 150000, seats: 120, eligibility: 'JEE Mains', degree: 'B.Tech' },
      { id: 'btech-civil', name: 'B.Tech Civil Engineering', duration: '4 Years', fees: 140000, seats: 90, eligibility: 'JEE Mains', degree: 'B.Tech' },
      { id: 'mba', name: 'MBA', duration: '2 Years', fees: 180000, seats: 60, eligibility: 'CAT', degree: 'MBA' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Sanjana Kumar', rating: 4, comment: 'NIT Trichy gave me a solid foundation. The placement cell is excellent and faculty is very supportive. Campus life is active and enriching.', date: '2024-02-20', helpful: 178, aspects: { academics: 4, campus: 4, placements: 4, faculty: 4 } },
    ],
  },
  {
    id: 'vit-vellore',
    name: 'Vellore Institute of Technology',
    shortName: 'VIT Vellore',
    location: 'Vellore, Tamil Nadu',
    city: 'Vellore',
    state: 'Tamil Nadu',
    fees: { min: 190000, max: 230000 },
    rating: 4.1,
    reviewCount: 5643,
    placementPercentage: 82,
    averagePackage: 8,
    highestPackage: 0,
    description: 'VIT University is one of India\'s largest private engineering universities. Known for its diverse student body, international collaborations, and strong industry ties. VIT has campuses in Vellore, Chennai, Amaravati, and Bhopal.',
    established: 1984,
    type: 'Deemed',
    accreditation: 'NAAC A++',
    nirfRank: 11,
    tags: ['VIT', 'Private', 'International Programs', 'Large Campus'],
    facilities: ['Super Market', 'Multiple Restaurants', 'Sports Complex', 'Hospital', 'Tech Park'],
    website: 'https://www.vit.ac.in',
    totalStudents: 35000,
    campusArea: '372 acres',
    topRecruiters: [
      { name: 'TCS', package: 7 },
      { name: 'Cognizant', package: 4.5 },
      { name: 'Accenture', package: 4.5 },
      { name: 'Capgemini', package: 4 },
      { name: 'Dell', package: 12 },
    ],
    courses: [
      { id: 'btech-cse', name: 'B.Tech CSE', duration: '4 Years', fees: 220000, seats: 1500, eligibility: 'VITEEE', degree: 'B.Tech' },
      { id: 'btech-aiml', name: 'B.Tech AI & Machine Learning', duration: '4 Years', fees: 230000, seats: 300, eligibility: 'VITEEE', degree: 'B.Tech' },
      { id: 'mca', name: 'MCA', duration: '2 Years', fees: 150000, seats: 120, eligibility: 'VITMEE', degree: 'MCA' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Aditya Kumar', rating: 4, comment: 'VIT has amazing infrastructure and a very lively campus. Lots of opportunities for extracurriculars. The tech park on campus is a great advantage.', date: '2024-03-10', helpful: 256, aspects: { academics: 3, campus: 5, placements: 4, faculty: 3 } },
    ],
  },
  {
    id: 'srm-kattankulathur',
    name: 'SRM Institute of Science and Technology',
    shortName: 'SRM University',
    location: 'Kattankulathur, Tamil Nadu',
    city: 'Kattankulathur',
    state: 'Tamil Nadu',
    fees: { min: 200000, max: 350000 },
    rating: 3.9,
    reviewCount: 4321,
    placementPercentage: 75,
    averagePackage: 6,
    highestPackage: 0,
    description: 'SRM Institute of Science and Technology is one of India\'s top ranked universities with over 52,000 students. Known for its modern infrastructure, research facilities, and international collaborations with universities worldwide.',
    established: 1985,
    type: 'Deemed',
    accreditation: 'NAAC A++',
    nirfRank: 36,
    tags: ['SRM', 'Private', 'Research', 'Global'],
    facilities: ['Smart Classrooms', 'Hospital', 'Sports Arena', 'Cultural Center'],
    website: 'https://www.srmist.edu.in',
    totalStudents: 52000,
    campusArea: '250 acres',
    topRecruiters: [
      { name: 'TCS', package: 7 },
      { name: 'Wipro', package: 6.5 },
      { name: 'Zoho', package: 12 },
      { name: 'HCL', package: 5 },
      { name: 'Mindtree', package: 8 },
    ],
    courses: [
      { id: 'btech-cse', name: 'B.Tech CSE', duration: '4 Years', fees: 280000, seats: 900, eligibility: 'SRMJEEE', degree: 'B.Tech' },
      { id: 'btech-ece', name: 'B.Tech ECE', duration: '4 Years', fees: 260000, seats: 600, eligibility: 'SRMJEEE', degree: 'B.Tech' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Deepika Singh', rating: 4, comment: 'SRM has a huge campus with lots of facilities. The international exposure is great. Placements are decent for top performers.', date: '2024-01-15', helpful: 134, aspects: { academics: 3, campus: 5, placements: 3, faculty: 3 } },
    ],
  },
  {
    id: 'iit-madras',
    name: 'Indian Institute of Technology Madras',
    shortName: 'IIT Madras',
    location: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    fees: { min: 185000, max: 235000 },
    rating: 4.8,
    reviewCount: 2654,
    placementPercentage: 96,
    averagePackage: 26,
    highestPackage: 2,
    description: 'IIT Madras, the #1 engineering institute in India as per NIRF, is situated in a beautifully forested campus in Chennai. Renowned for world-class research, innovation, and its startup ecosystem with the Research Park.',
    established: 1959,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 1,
    tags: ['IIT', 'NIRF #1', 'Govt. Funded', 'Startup Ecosystem'],
    facilities: ['Research Park', 'Forest Campus', 'Olympic Pool', 'Deer Park', 'Hospital'],
    website: 'https://www.iitm.ac.in',
    totalStudents: 9500,
    campusArea: '617 acres',
    topRecruiters: [
      { name: 'Google', package: 140 },
      { name: 'Microsoft', package: 100 },
      { name: 'Meta', package: 110 },
      { name: 'Flipkart', package: 60 },
      { name: 'Tower Research', package: 120 },
    ],
    courses: [
      { id: 'btech-cs', name: 'B.Tech Computer Science', duration: '4 Years', fees: 220000, seats: 112, eligibility: 'JEE Advanced', degree: 'B.Tech' },
      { id: 'btech-ae', name: 'B.Tech Aerospace Engineering', duration: '4 Years', fees: 210000, seats: 70, eligibility: 'JEE Advanced', degree: 'B.Tech' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Meera Krishnan', rating: 5, comment: 'IIT Madras has a stunning forested campus. Research opportunities are incredible. The Research Park creates amazing startup culture.', date: '2024-04-01', helpful: 387, aspects: { academics: 5, campus: 5, placements: 5, faculty: 5 } },
    ],
  },
  {
    id: 'iim-bangalore',
    name: 'Indian Institute of Management Bangalore',
    shortName: 'IIM Bangalore',
    location: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    fees: { min: 2300000, max: 2500000 },
    rating: 4.8,
    reviewCount: 1654,
    placementPercentage: 100,
    averagePackage: 33,
    highestPackage: 75,
    description: 'IIM Bangalore is one of India\'s top business schools, known for its entrepreneurship ecosystem, social impact initiatives, and strong alumni network in the Silicon Valley of India.',
    established: 1973,
    type: 'Government',
    accreditation: 'AACSB, AMBA, EQUIS',
    nirfRank: 2,
    tags: ['IIM', 'Top MBA', 'Entrepreneurship', 'Tech Hub'],
    facilities: ['Library', 'Sports Complex', 'Hostel', 'NSRCEL', 'Digital Learning'],
    website: 'https://www.iimb.ac.in',
    totalStudents: 1400,
    campusArea: '100 acres',
    topRecruiters: [
      { name: 'McKinsey', package: 75 },
      { name: 'BCG', package: 72 },
      { name: 'Amazon', package: 50 },
      { name: 'Flipkart', package: 45 },
      { name: 'PhonePe', package: 42 },
    ],
    courses: [
      { id: 'pgp', name: 'Post Graduate Programme', duration: '2 Years', fees: 2400000, seats: 412, eligibility: 'CAT', degree: 'MBA' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Ankit Gupta', rating: 5, comment: 'IIMB in Bangalore is perfect. Being in the tech capital means amazing industry exposure. NSRCEL for entrepreneurs is world-class.', date: '2024-02-28', helpful: 342, aspects: { academics: 5, campus: 5, placements: 5, faculty: 5 } },
    ],
  },
  {
    id: 'nit-warangal',
    name: 'National Institute of Technology Warangal',
    shortName: 'NIT Warangal',
    location: 'Warangal, Telangana',
    city: 'Warangal',
    state: 'Telangana',
    fees: { min: 115000, max: 170000 },
    rating: 4.3,
    reviewCount: 1543,
    placementPercentage: 84,
    averagePackage: 11,
    highestPackage: 0,
    description: 'NIT Warangal, one of the oldest NITs, is known for its strong engineering programs, excellent research, and vibrant student life. Located in the historic city of Warangal in Telangana.',
    established: 1959,
    type: 'Government',
    accreditation: 'NAAC A',
    nirfRank: 30,
    tags: ['NIT', 'Govt. Funded', 'Research', 'Historical'],
    facilities: ['Central Library', 'Sports Complex', 'Hostel', 'Innovation Center'],
    website: 'https://www.nitw.ac.in',
    totalStudents: 7000,
    campusArea: '248 acres',
    topRecruiters: [
      { name: 'Microsoft', package: 42 },
      { name: 'Amazon', package: 35 },
      { name: 'Samsung', package: 20 },
      { name: 'TCS', package: 7 },
      { name: 'Deloitte', package: 10 },
    ],
    courses: [
      { id: 'btech-cse', name: 'B.Tech CSE', duration: '4 Years', fees: 150000, seats: 120, eligibility: 'JEE Mains', degree: 'B.Tech' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Ravi Teja', rating: 4, comment: 'NIT Warangal has a great academic environment. Faculty is knowledgeable and placements are improving rapidly.', date: '2024-01-30', helpful: 145, aspects: { academics: 4, campus: 3, placements: 4, faculty: 4 } },
    ],
  },
  {
    id: 'iit-kharagpur',
    name: 'Indian Institute of Technology Kharagpur',
    shortName: 'IIT Kharagpur',
    location: 'Kharagpur, West Bengal',
    city: 'Kharagpur',
    state: 'West Bengal',
    fees: { min: 180000, max: 230000 },
    rating: 4.6,
    reviewCount: 3021,
    placementPercentage: 95,
    averagePackage: 25,
    highestPackage: 1,
    description: 'IIT Kharagpur, the first IIT established in India (1951), is the largest IIT in terms of campus area. Known for its rich legacy, diverse programs including law and medicine, and outstanding research.',
    established: 1951,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 5,
    tags: ['IIT', 'Oldest IIT', 'NIRF Top 10', 'Legacy'],
    facilities: ['Multiple Libraries', 'Stadium', 'Hospital', 'Airport-like Size Campus', 'Multiple Research Parks'],
    website: 'https://www.iitkgp.ac.in',
    totalStudents: 13000,
    campusArea: '2100 acres',
    topRecruiters: [
      { name: 'Google', package: 100 },
      { name: 'Uber', package: 85 },
      { name: 'Samsung', package: 62 },
      { name: 'ISRO', package: 12 },
      { name: 'Goldman Sachs', package: 75 },
    ],
    courses: [
      { id: 'btech-cs', name: 'B.Tech Computer Science', duration: '4 Years', fees: 210000, seats: 100, eligibility: 'JEE Advanced', degree: 'B.Tech' },
      { id: 'law', name: 'B.A. LL.B. (Hons.)', duration: '5 Years', fees: 150000, seats: 50, eligibility: 'CLAT', degree: 'LL.B' },
      { id: 'mbbs', name: 'MBBS', duration: '5.5 Years', fees: 120000, seats: 50, eligibility: 'NEET', degree: 'MBBS' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Shubham Das', rating: 5, comment: 'KGP is a city in itself! The campus is massive and the student culture is incredible. Technology Student\'s Gymkhana activities are legendary.', date: '2024-03-20', helpful: 289, aspects: { academics: 5, campus: 5, placements: 5, faculty: 4 } },
    ],
  },
  {
    id: 'manipal-university',
    name: 'Manipal Academy of Higher Education',
    shortName: 'Manipal University',
    location: 'Manipal, Karnataka',
    city: 'Manipal',
    state: 'Karnataka',
    fees: { min: 350000, max: 800000 },
    rating: 4.0,
    reviewCount: 3876,
    placementPercentage: 78,
    averagePackage: 7,
    highestPackage: 0,
    description: 'Manipal Academy is a prestigious deemed university with programs in engineering, medicine, dentistry, and management. Known for its student-friendly campus, diverse student population, and strong alumni network.',
    established: 1953,
    type: 'Deemed',
    accreditation: 'NAAC A+',
    nirfRank: 7,
    tags: ['Deemed', 'Medical', 'Engineering', 'International'],
    facilities: ['Kasturba Hospital', 'Sports Complex', 'Shopping Center', 'Multiple Restaurants'],
    website: 'https://manipal.edu',
    totalStudents: 28000,
    campusArea: '600 acres',
    topRecruiters: [
      { name: 'TCS', package: 7 },
      { name: 'Infosys', package: 7 },
      { name: 'Accenture', package: 4.5 },
      { name: 'Goldman Sachs', package: 25 },
      { name: 'Microsoft', package: 40 },
    ],
    courses: [
      { id: 'btech-cse', name: 'B.Tech CSE', duration: '4 Years', fees: 400000, seats: 300, eligibility: 'MET', degree: 'B.Tech' },
      { id: 'mbbs', name: 'MBBS', duration: '5.5 Years', fees: 800000, seats: 150, eligibility: 'NEET', degree: 'MBBS' },
      { id: 'mba', name: 'MBA', duration: '2 Years', fees: 600000, seats: 120, eligibility: 'CAT/MAT', degree: 'MBA' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Rhea Fernandez', rating: 4, comment: 'Manipal is a self-sufficient university town. The exposure you get here is incredible. Great for making lifelong friendships and networking.', date: '2024-02-05', helpful: 201, aspects: { academics: 3, campus: 5, placements: 3, faculty: 4 } },
    ],
  },
  {
    id: 'iit-roorkee',
    name: 'Indian Institute of Technology Roorkee',
    shortName: 'IIT Roorkee',
    location: 'Roorkee, Uttarakhand',
    city: 'Roorkee',
    state: 'Uttarakhand',
    fees: { min: 195000, max: 245000 },
    rating: 4.5,
    reviewCount: 2187,
    placementPercentage: 94,
    averagePackage: 22,
    highestPackage: 1,
    description: 'IIT Roorkee, established in 1847, is the oldest technical institution in Asia. Known for its rich heritage, beautiful campus with Gothic architecture, and strong programs in engineering and architecture.',
    established: 1847,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 6,
    tags: ['IIT', 'Oldest Technical Institute', 'NIRF Top 10', 'Heritage'],
    facilities: ['Heritage Campus', 'Research Labs', 'Sports Complex', 'Hostel'],
    website: 'https://www.iitr.ac.in',
    totalStudents: 9200,
    campusArea: '365 acres',
    topRecruiters: [
      { name: 'Microsoft', package: 88 },
      { name: 'Amazon', package: 65 },
      { name: 'Adobe', package: 52 },
      { name: 'Schlumberger', package: 28 },
      { name: 'Qualcomm', package: 45 },
    ],
    courses: [
      { id: 'btech-cs', name: 'B.Tech Computer Science', duration: '4 Years', fees: 225000, seats: 80, eligibility: 'JEE Advanced', degree: 'B.Tech' },
      { id: 'b-arch', name: 'B. Architecture', duration: '5 Years', fees: 180000, seats: 40, eligibility: 'JEE Advanced + NATA', degree: 'B.Arch' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Vaibhav Sharma', rating: 5, comment: 'IIT Roorkee\'s Gothic architecture is breathtaking. The institute has a perfect blend of tradition and modern education.', date: '2024-04-08', helpful: 234, aspects: { academics: 5, campus: 5, placements: 4, faculty: 5 } },
    ],
  },
  {
    id: 'du-delhi',
    name: 'University of Delhi',
    shortName: 'Delhi University',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    fees: { min: 15000, max: 80000 },
    rating: 4.2,
    reviewCount: 8765,
    placementPercentage: 72,
    averagePackage: 7,
    highestPackage: 0,
    description: 'University of Delhi is one of India\'s most prestigious central universities, with a legacy of over 100 years. Home to iconic colleges like Hindu, St. Stephen\'s, and Miranda House. Known for humanities, commerce, and science programs.',
    established: 1922,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 9,
    tags: ['Central University', 'Century Old', 'Prestigious', 'Arts & Commerce'],
    facilities: ['Multiple Libraries', 'Sports Facilities', 'Cultural Festivals', 'Iconic Campus'],
    website: 'https://www.du.ac.in',
    totalStudents: 300000,
    campusArea: '160 acres',
    topRecruiters: [
      { name: 'Deloitte', package: 12 },
      { name: 'EY', package: 10 },
      { name: 'HUL', package: 15 },
      { name: 'KPMG', package: 11 },
      { name: 'Times Group', package: 8 },
    ],
    courses: [
      { id: 'bcom-h', name: 'B.Com (Honours)', duration: '3 Years', fees: 25000, seats: 2000, eligibility: 'CUET', degree: 'B.Com' },
      { id: 'ba-eco', name: 'B.A. Economics (Honours)', duration: '3 Years', fees: 20000, seats: 1500, eligibility: 'CUET', degree: 'B.A.' },
      { id: 'bsc-cs', name: 'B.Sc. Computer Science', duration: '3 Years', fees: 30000, seats: 500, eligibility: 'CUET', degree: 'B.Sc.' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Aditi Bose', rating: 4, comment: 'Delhi University is a complete experience. The cultural diversity, Fest culture, and the prestige of DU colleges is unparalleled anywhere in India.', date: '2024-03-25', helpful: 543, aspects: { academics: 4, campus: 4, placements: 3, faculty: 4 } },
    ],
  },
  {
    id: 'iit-kanpur',
    name: 'Indian Institute of Technology Kanpur',
    shortName: 'IIT Kanpur',
    location: 'Kanpur, Uttar Pradesh',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    fees: { min: 200000, max: 250000 },
    rating: 4.7,
    reviewCount: 2345,
    placementPercentage: 96,
    averagePackage: 24,
    highestPackage: 1,
    description: 'IIT Kanpur was established with unique American collaboration in 1959. It was the first IIT to offer Computer Science as a discipline and has been at the forefront of AI, aerospace, and cybersecurity research.',
    established: 1959,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 4,
    tags: ['IIT', 'Pioneer CS', 'NIRF Top 5', 'Startup Friendly'],
    facilities: ['Aircraft Hangar', 'Innovation Hub', 'Open Air Theater', 'Observatory'],
    website: 'https://www.iitk.ac.in',
    totalStudents: 8800,
    campusArea: '1055 acres',
    topRecruiters: [
      { name: 'Google', package: 125 },
      { name: 'Two Sigma', package: 150 },
      { name: 'Palantir', package: 90 },
      { name: 'Microsoft', package: 85 },
      { name: 'WorldQuant', package: 100 },
    ],
    courses: [
      { id: 'btech-cs', name: 'B.Tech Computer Science', duration: '4 Years', fees: 230000, seats: 90, eligibility: 'JEE Advanced', degree: 'B.Tech' },
      { id: 'btech-aero', name: 'B.Tech Aerospace Engineering', duration: '4 Years', fees: 215000, seats: 60, eligibility: 'JEE Advanced', degree: 'B.Tech' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Priyank Joshi', rating: 5, comment: 'IITK\'s freedom and open culture is phenomenal. Two Sigma and WorldQuant hiring here shows the quality. Research culture is top-notch.', date: '2024-03-12', helpful: 312, aspects: { academics: 5, campus: 4, placements: 5, faculty: 5 } },
    ],
  },
  {
    id: 'srcc-delhi',
    name: 'Shri Ram College of Commerce',
    shortName: 'SRCC Delhi',
    location: 'New Delhi, Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    fees: { min: 20000, max: 35000 },
    rating: 4.6,
    reviewCount: 3456,
    placementPercentage: 90,
    averagePackage: 15,
    highestPackage: 0,
    description: 'SRCC is India\'s premier commerce college and one of the top-ranked colleges under Delhi University. Known for its exceptional B.Com (Hons) and Economics programs, and its legendary alumni in business and finance.',
    established: 1926,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 12,
    tags: ['Commerce', 'NIRF Top 15', 'Finance Hub', 'DU College'],
    facilities: ['Library', 'Auditorium', 'Cafeteria', 'Commerce Lab'],
    website: 'https://www.srcc.edu',
    totalStudents: 2500,
    campusArea: '5 acres',
    topRecruiters: [
      { name: 'Goldman Sachs', package: 30 },
      { name: 'McKinsey', package: 25 },
      { name: 'EY', package: 12 },
      { name: 'KPMG', package: 11 },
      { name: 'Deloitte', package: 12 },
    ],
    courses: [
      { id: 'bcom-h', name: 'B.Com (Honours)', duration: '3 Years', fees: 22000, seats: 430, eligibility: 'CUET', degree: 'B.Com' },
      { id: 'ba-eco', name: 'B.A. Economics (Honours)', duration: '3 Years', fees: 18000, seats: 110, eligibility: 'CUET', degree: 'B.A.' },
      { id: 'mcom', name: 'M.Com', duration: '2 Years', fees: 28000, seats: 80, eligibility: 'Graduation', degree: 'M.Com' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Anika Malhotra', rating: 5, comment: 'SRCC is legendary in the commerce world. The faculty is exceptional and the alumni network is priceless. Best decision of my life.', date: '2024-04-15', helpful: 389, aspects: { academics: 5, campus: 3, placements: 5, faculty: 5 } },
    ],
  },
  {
    id: 'amity-noida',
    name: 'Amity University Noida',
    shortName: 'Amity University',
    location: 'Noida, Uttar Pradesh',
    city: 'Noida',
    state: 'Uttar Pradesh',
    fees: { min: 250000, max: 450000 },
    rating: 3.7,
    reviewCount: 4213,
    placementPercentage: 68,
    averagePackage: 5,
    highestPackage: 0,
    description: 'Amity University is one of India\'s largest private universities with a focus on holistic education, international exposure, and industry-academia interface. Known for its beautiful campus and strong mass media/law programs.',
    established: 2005,
    type: 'Private',
    accreditation: 'NAAC A+',
    nirfRank: 55,
    tags: ['Private', 'International', 'Mass Media', 'Law'],
    facilities: ['World-Class Campus', 'Indoor Stadium', 'Multiple Restaurants', 'Shopping Complex'],
    website: 'https://www.amity.edu',
    totalStudents: 60000,
    campusArea: '150 acres',
    topRecruiters: [
      { name: 'TCS', package: 6 },
      { name: 'Wipro', package: 5.5 },
      { name: 'Cognizant', package: 5 },
      { name: 'EY', package: 8 },
      { name: 'Deloitte', package: 8 },
    ],
    courses: [
      { id: 'btech-cse', name: 'B.Tech CSE', duration: '4 Years', fees: 320000, seats: 500, eligibility: 'JEE Mains/Merit', degree: 'B.Tech' },
      { id: 'bba', name: 'BBA', duration: '3 Years', fees: 250000, seats: 300, eligibility: 'Merit', degree: 'BBA' },
      { id: 'llb', name: 'B.A. LL.B.', duration: '5 Years', fees: 280000, seats: 200, eligibility: 'CLAT', degree: 'LL.B' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Rahul Gupta', rating: 3, comment: 'Amity has good facilities and a vibrant campus life. Academics could be stronger. The international exposure programs are a great plus.', date: '2024-02-15', helpful: 156, aspects: { academics: 3, campus: 4, placements: 3, faculty: 3 } },
    ],
  },
  {
    id: 'iit-hyderabad',
    name: 'Indian Institute of Technology Hyderabad',
    shortName: 'IIT Hyderabad',
    location: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    fees: { min: 175000, max: 220000 },
    rating: 4.3,
    reviewCount: 1234,
    placementPercentage: 90,
    averagePackage: 20,
    highestPackage: 1,
    description: 'IIT Hyderabad is a new-generation IIT rapidly building its reputation for cutting-edge research in AI, ML, and data sciences. Located in the tech hub of Hyderabad with excellent industry connections.',
    established: 2008,
    type: 'Government',
    accreditation: 'NAAC A',
    nirfRank: 17,
    tags: ['IIT', 'New IIT', 'AI Research', 'Tech Hub'],
    facilities: ['Research Labs', 'Sports Complex', 'Hostel', 'Innovation Center'],
    website: 'https://www.iith.ac.in',
    totalStudents: 4500,
    campusArea: '580 acres',
    topRecruiters: [
      { name: 'Google', package: 120 },
      { name: 'Microsoft', package: 90 },
      { name: 'Samsung', package: 55 },
      { name: 'Amazon', package: 60 },
      { name: 'Qualcomm', package: 50 },
    ],
    courses: [
      { id: 'btech-cs', name: 'B.Tech Computer Science', duration: '4 Years', fees: 200000, seats: 80, eligibility: 'JEE Advanced', degree: 'B.Tech' },
      { id: 'mtech-ai', name: 'M.Tech AI & ML', duration: '2 Years', fees: 150000, seats: 40, eligibility: 'GATE', degree: 'M.Tech' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Sriram Reddy', rating: 4, comment: 'IIT Hyderabad is growing rapidly. The AI/ML research facilities are state-of-the-art. Being in Hyderabad gives amazing internship opportunities.', date: '2024-03-05', helpful: 187, aspects: { academics: 4, campus: 4, placements: 4, faculty: 4 } },
    ],
  },
  {
    id: 'mu-mumbai',
    name: 'University of Mumbai',
    shortName: 'Mumbai University',
    location: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    fees: { min: 10000, max: 120000 },
    rating: 3.8,
    reviewCount: 12543,
    placementPercentage: 65,
    averagePackage: 5,
    highestPackage: 0,
    description: 'University of Mumbai, one of the largest universities in the world by student enrollment, offers a wide range of programs through its affiliated colleges across Mumbai, Thane, and Raigad districts.',
    established: 1857,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 20,
    tags: ['Central University', 'Oldest', 'Affiliated', 'Heritage'],
    facilities: ['Fort Campus', 'Multiple Libraries', 'Heritage Buildings'],
    website: 'https://mu.ac.in',
    totalStudents: 800000,
    campusArea: '230 acres',
    topRecruiters: [
      { name: 'TCS', package: 6 },
      { name: 'HDFC', package: 5 },
      { name: 'Deloitte', package: 8 },
      { name: 'EY', package: 7 },
      { name: 'Wipro', package: 5.5 },
    ],
    courses: [
      { id: 'bsc-cs', name: 'B.Sc. Computer Science', duration: '3 Years', fees: 35000, seats: 1000, eligibility: 'HSC/12th', degree: 'B.Sc.' },
      { id: 'bcom', name: 'B.Com', duration: '3 Years', fees: 15000, seats: 5000, eligibility: 'HSC/12th', degree: 'B.Com' },
      { id: 'be-it', name: 'B.E. Information Technology', duration: '4 Years', fees: 100000, seats: 500, eligibility: 'JEE Mains/Merit', degree: 'B.E.' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Vikram Joshi', rating: 4, comment: 'Mumbai University affiliated colleges are very diverse. The Fort campus is stunning. Depends a lot on which affiliated college you get into.', date: '2024-01-25', helpful: 678, aspects: { academics: 3, campus: 4, placements: 3, faculty: 3 } },
    ],
  },
  {
    id: 'pes-bangalore',
    name: 'PES University',
    shortName: 'PES University',
    location: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    fees: { min: 300000, max: 500000 },
    rating: 4.0,
    reviewCount: 2876,
    placementPercentage: 80,
    averagePackage: 9,
    highestPackage: 0,
    description: 'PES University is one of Bangalore\'s top private engineering colleges, known for excellent placements in the tech industry, modern curriculum with focus on AI and Data Science.',
    established: 1988,
    type: 'Deemed',
    accreditation: 'NAAC A+',
    nirfRank: 68,
    tags: ['Private', 'Tech Hub', 'Placements', 'Bangalore'],
    facilities: ['Modern Labs', 'Sports Complex', 'Hostel', 'Cafeteria'],
    website: 'https://pes.edu',
    totalStudents: 8000,
    campusArea: '20 acres',
    topRecruiters: [
      { name: 'Amazon', package: 25 },
      { name: 'Flipkart', package: 20 },
      { name: 'Wipro', package: 7 },
      { name: 'Infosys', package: 7 },
      { name: 'Microsoft', package: 45 },
    ],
    courses: [
      { id: 'btech-cse', name: 'B.Tech CSE', duration: '4 Years', fees: 380000, seats: 480, eligibility: 'PESSAT', degree: 'B.Tech' },
      { id: 'btech-aiml', name: 'B.Tech AI & ML', duration: '4 Years', fees: 420000, seats: 120, eligibility: 'PESSAT', degree: 'B.Tech' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Kavitha Raj', rating: 4, comment: 'PES is a great college in Bangalore. The placement record is solid and faculty is industry-experienced. Best for those who want to work in tech.', date: '2024-02-22', helpful: 213, aspects: { academics: 4, campus: 3, placements: 4, faculty: 4 } },
    ],
  },
  {
    id: 'jadavpur-university',
    name: 'Jadavpur University',
    shortName: 'Jadavpur University',
    location: 'Kolkata, West Bengal',
    city: 'Kolkata',
    state: 'West Bengal',
    fees: { min: 8000, max: 50000 },
    rating: 4.3,
    reviewCount: 3210,
    placementPercentage: 82,
    averagePackage: 10,
    highestPackage: 0,
    description: 'Jadavpur University is one of the finest state universities in India, known for its engineering, science, and arts programs. It produces some of the brightest minds who go on to IITs, IIMs, and global universities.',
    established: 1955,
    type: 'Government',
    accreditation: 'NAAC A',
    nirfRank: 14,
    tags: ['State University', 'NIRF Top 15', 'Research', 'Affordable'],
    facilities: ['Multiple Libraries', 'Research Centers', 'Sports Ground', 'Hostel'],
    website: 'https://jadavpuruniversity.in',
    totalStudents: 18000,
    campusArea: '63 acres',
    topRecruiters: [
      { name: 'TCS', package: 7 },
      { name: 'Infosys', package: 7 },
      { name: 'Wipro', package: 6.5 },
      { name: 'Amazon', package: 30 },
      { name: 'Samsung R&D', package: 22 },
    ],
    courses: [
      { id: 'be-cse', name: 'B.E. Computer Science', duration: '4 Years', fees: 30000, seats: 90, eligibility: 'WBJEE', degree: 'B.E.' },
      { id: 'be-ece', name: 'B.E. Electronics', duration: '4 Years', fees: 28000, seats: 80, eligibility: 'WBJEE', degree: 'B.E.' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Subhrajit Dey', rating: 4, comment: 'JU is among the best government colleges in India. At this fee, you get world-class education. The campus culture and faculty are excellent.', date: '2024-04-02', helpful: 298, aspects: { academics: 5, campus: 3, placements: 3, faculty: 5 } },
    ],
  },
  {
    id: 'thapar-patiala',
    name: 'Thapar Institute of Engineering and Technology',
    shortName: 'Thapar University',
    location: 'Patiala, Punjab',
    city: 'Patiala',
    state: 'Punjab',
    fees: { min: 380000, max: 440000 },
    rating: 4.1,
    reviewCount: 2134,
    placementPercentage: 83,
    averagePackage: 10,
    highestPackage: 0,
    description: 'Thapar Institute is one of the top private engineering colleges in North India. Known for its excellent faculty, good industry connections, and campus with modern facilities in the royal city of Patiala.',
    established: 1956,
    type: 'Deemed',
    accreditation: 'NAAC A',
    nirfRank: 28,
    tags: ['North India', 'Private', 'Engineering', 'Patiala'],
    facilities: ['Smart Campus', 'Sports Complex', 'Hostel', 'Innovation Center'],
    website: 'https://www.thapar.edu',
    totalStudents: 12000,
    campusArea: '250 acres',
    topRecruiters: [
      { name: 'Amazon', package: 30 },
      { name: 'Microsoft', package: 45 },
      { name: 'Wipro', package: 7 },
      { name: 'Samsung', package: 18 },
      { name: 'Infosys', package: 7 },
    ],
    courses: [
      { id: 'btech-cse', name: 'B.Tech CSE', duration: '4 Years', fees: 420000, seats: 240, eligibility: 'JEE Mains', degree: 'B.Tech' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Harpreet Kaur', rating: 4, comment: 'Thapar is a great college for engineering in North India. The campus is beautiful and faculty is supportive. Good placements for top performers.', date: '2024-03-18', helpful: 167, aspects: { academics: 4, campus: 4, placements: 4, faculty: 4 } },
    ],
  },
  {
    id: 'iit-guwahati',
    name: 'Indian Institute of Technology Guwahati',
    shortName: 'IIT Guwahati',
    location: 'Guwahati, Assam',
    city: 'Guwahati',
    state: 'Assam',
    fees: { min: 185000, max: 230000 },
    rating: 4.4,
    reviewCount: 1876,
    placementPercentage: 92,
    averagePackage: 21,
    highestPackage: 1,
    description: 'IIT Guwahati, situated on the banks of the Brahmaputra river, is one of the most scenic IIT campuses. Known for excellent research, vibrant cultural scene, and strong industry connections in the Northeast.',
    established: 1994,
    type: 'Government',
    accreditation: 'NAAC A++',
    nirfRank: 7,
    tags: ['IIT', 'Scenic Campus', 'Northeast', 'NIRF Top 10'],
    facilities: ['Riverside Campus', 'Research Labs', 'Sports Complex', 'Innovation Center'],
    website: 'https://www.iitg.ac.in',
    totalStudents: 7000,
    campusArea: '285 acres',
    topRecruiters: [
      { name: 'Google', package: 110 },
      { name: 'Microsoft', package: 88 },
      { name: 'Flipkart', package: 55 },
      { name: 'Goldman Sachs', package: 65 },
      { name: 'Oracle', package: 40 },
    ],
    courses: [
      { id: 'btech-cs', name: 'B.Tech Computer Science', duration: '4 Years', fees: 210000, seats: 85, eligibility: 'JEE Advanced', degree: 'B.Tech' },
    ],
    reviews: [
      { id: 'r1', userId: 'u1', userName: 'Priyanka Baruah', rating: 4, comment: 'IIT Guwahati is simply beautiful. The Brahmaputra campus views are stunning. Excellent academics and good placement opportunities.', date: '2024-04-10', helpful: 245, aspects: { academics: 4, campus: 5, placements: 4, faculty: 4 } },
    ],
  },
];
